### PR TITLE
Section Table and Storybook Component

### LINKED ISSUE #16: Add Course Table Component
Add new component that renders a course table with section info. Assume that the data passed to the component called sections is a list of javascript objects, in the same format that is agreed on that the new API endpoint will return.

- [x] There is a section table component. 
- [x] There are fixtures for the table.
- [x] There is a storybook component for SectionTable.
- [x] `npm run storybook` runs without errors
- [x] There are tests such that `npm test`, `npm run coverage`, `npx stryker run` all pass; have full mutation and line coverage.

### PR DESCRIPTION
**Pull request by roberto-garcia-0**
# Overview

This PR implements a Section Table component that can display Section information. It also adds the corresponding storybook component for interactive testing without the backend. 

### 🖍️ Comment on any changes you would like to see! 🖍️

# Issues Addressed

Closes #16 

# Link to Storybook

[Section Table Storybook](https://ucsb-cs156-s22.github.io/s22-4pm-courses-docs-qa/storybook-qa/rg-section-table/?path)

# Details

## 🔥 NEW Section Table

Screenshot_20220528_010657

# Test Plan (for interactive testing) (Storybook Only)

1. Proceed to [Storybook Link](https://ucsb-cs156-s22.github.io/s22-4pm-courses-docs-qa/storybook-qa/rg-section-table/?path=%2Fstory%2Fcomponents-sections-sectionstable--empty)
2. Verify that there are section tables with:
    - no entries and just the labels
    - 1 entry and the labels
    - 3 entries and the labels
    - 5 entries and the labels
    - more than 5 entries and the labels

### CODE REVIEW

**Review by DistractedPrimate — APPROVED** [review]
This all looks good to me. Storybook looks good!

**Review by pconrad — COMMENTED** [review]
I'm still looking through this.. but so far I'm very impressed.   This is nice work.

**Review by pconrad — APPROVED** [review]
I can see where there may be "design choices" for the table that you may want to make differently in future versions (for example, instead of having an "isSection" column, perhaps using colors, fonts, indentation, alignment or other visual cues to link together a "lecture" section with it's associated "discussion" sections.

But that can be a separate issue!   This looks really good.  I'm particularly impressed with the way the PR was written up, and the fact that you included tests and stories.

**Comment by pconrad** [comment]
Well done!

**Pull request merged**
